description = "Ubuntu bionic base image and tiny runtime image with buildpacks for Java"

[lifecycle]
  version = "0.7.0"

[[buildpacks]]
  id = "org.cloudfoundry.openjdk"
  uri = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.2.11.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.buildsystem"
  uri = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.2.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jvmapplication"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.1.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.tomcat"
  uri = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.3.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.springboot"
  uri = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.2.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.distzip"
  uri = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.1.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.procfile"
  uri = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.1.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.debug"
  uri = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.2.8.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jdbc"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.1.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jmx"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.1.9.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.springautoreconfiguration"
  uri = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.1.8.tgz"

[[order]]
  [[order.group]]
    id = "org.cloudfoundry.openjdk"
    version = "1.2.11"

  [[order.group]]
    id = "org.cloudfoundry.buildsystem"
    version = "1.2.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.jvmapplication"
    version = "1.1.9"

  [[order.group]]
    id = "org.cloudfoundry.tomcat"
    version = "1.3.9"

  [[order.group]]
    id = "org.cloudfoundry.springboot"
    version = "1.2.9"

  [[order.group]]
    id = "org.cloudfoundry.distzip"
    version = "1.1.9"

  [[order.group]]
    id = "org.cloudfoundry.procfile"
    version = "1.1.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.debug"
    version = "1.2.8"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.jdbc"
    version = "1.1.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.jmx"
    version = "1.1.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.springautoreconfiguration"
    version = "1.1.8"
    optional = true

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "humourmind/cnb-build:tiny"
  run-image = "humourmind/cnb-run:tiny"
